<?php
/**
 * module-reference:/bootstrap/app.phtml
 *
 * @created   2017-12-06
 * @version   1.0
 * @package   module-reference
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<p>
	Your application has not been initialized to rewrite of route.
	That is for dispatching to end-point.
	Please access application root. How to setting will be introduced.
</p>
