<?php
/**
 * app-skeleton-3:/html/reference/core.phtml
 *
 * @creation  2017-09-16
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<h2>Core</h2>
<div data-i18n="true" data-lang="en">
	<p>Now written!!</p>
	<p>
		The Core is onepiece-framework's core program.
	</p>
	<ol>
		<li>Autoloader.class.php</li>
		<li>Bootstrap.php</li>
		<li>Cookie.class.php</li>
		<li>Defines.php</li>
		<li>Developer.class.php</li>
		<li>EMail.class.php</li>
		<li>Env.class.php</li>
		<li>Error.php</li>
		<li>Functions.php</li>
		<li>Notice.class.php</li>
		<li>OP_CORE.trait.php</li>
		<li>OP_SESSION.trait.php</li>
		<li>Time.class.php</li>
		<li>Unit.class.php</li>
	</ol>
</div>
