<?php
/**
 * module-reference:/index.phtml
 *
 * @creation  2019-03-29
 * @version   1.0
 * @package   module-reference
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $app \OP\UNIT\App */
?>
<section class="reference">
	<!-- left menu -->
	<?= $app->Template('index-menu-left.phtml') ?>

	<!-- main content -->
	<section class="main">
		<h1>The onepiece-framework reference book.</h1>
	</section>
</section>
