<?php
/**
 * app-skeleton-3:/html/reference/introduction.phtml
 *
 * @creation  2017-09-14
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section data-i18n="true" data-lang="en">
	<h2>Introduction - Our </>onepiece-framework</> is insanely great!!</h2>
	<p>Our "onepiece-framework" will destructive innovation.</p>
	<p>"onepiece-framework" is consists of the following elements.</p>
</section>
<div data-i18n="false" data-lang="en">
	<ol>
		<li>Core</li>
		<li>App</li>
		<li>Unit</li>
		<li>Module</li>
	</ol>
</div>
<div role="markdown">
	* App
		* i18n
	* Unit
		* DB
		* SQL
		* Form
		* Validate
	* Module
		* Login
		* Short URL
		* Comment leave
		* Communication
</div>
<div data-i18n="true" data-lang="en">
	<p>
		Features of "onepiece-framework" are as follows.
	</p>
	<ul>
		<li>Permanetly single version. (Rolling update)</li>
		<li>Intuitive file, class, method</li>
	</ul>
</div>
