<?php
/** op-module-reference:/menu-right.phtml
 *
 * @created   2018-11-01
 * @version   1.0
 * @package   op-module-reference
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** Namespace
 *
 */
namespace OP;

?>
<section id="menu-right" class="menu-right">
	<ol>
		<?php foreach( ['core','unit','layout','module'] as $key ): ?>
			<li data-meta="<?= $key ?>"><?= $key ?></li>
		<?php endforeach; ?>
	</ol>
</section>
