<?php
/**
 * module-reference:/menu.phtml
 *
 * @created   2018-10-30
 * @updated   2019-03-29
 * @version   1.0
 * @package   module-reference
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<menu>
	<ol>
		<li><a href="/reference/introduction">Introduction</a></li>
		<li><a href="/reference/core">Core</a></li>
		<li><a href="/reference/app">App</a></li>
		<li>
			<a href="/reference/unit">Unit</a>
			<ul>
				<li><a href="/reference/unit/newworld">NewWorld</a></li>
				<li><a href="/reference/unit/db">Database</a></li>
				<li><a href="/reference/unit/sql">SQL</a></li>
				<li><a href="/reference/unit/form">Form</a></li>
				<li><a href="/reference/unit/validate">Validate</a></li>
			</ul>
		</li>
	</ol>
</menu>
