<?php
/**
 * module-reference:/menu-right.phtml
 *
 * @created   2018-11-01
 * @version   1.0
 * @package   module-reference
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** Namespace
 *
 */
namespace OP;

?>
<section id="menu-right" class="menu-right" data-i18n="deny">
	<ol>
		<li>
			<span role="link" data-md="app">App</span>
			<ol>
				<?php foreach( glob( RootPath('asset') . '/readme/*\.md' ) as $md ): ?>
				<?php $md = basename($md, '.md') ?>
				<li role="link" data-md="app-<?= $md ?>"><?= $md ?></li>
				<?php endforeach; ?>
			</ol>
		</li>
		<li>
			<span role="link" data-md="core">Core</span>
			<ol>
				<?php foreach( glob( RootPath('asset') . '/core/readme/*\.md' ) as $md ): ?>
				<?php $md = basename($md, '.md') ?>
				<li role="link" data-md="core-<?= $md ?>"><?= $md ?></li>
				<?php endforeach; ?>
			</ol>
		</li>
		<li>
			Unit
			<ol>
				<?php foreach( glob( RootPath('asset') . '/unit/*' ) as $unit ): ?>
				<?php $unit = basename($unit) ?>
				<li role="link" data-md="unit-<?= $unit ?>"><?= $unit ?></li>
				<?php endforeach; ?>
			</ol>
		</li>
		<li>
			<span role="link" data-md="javascript">JavaScript</span>
		</li>
	</ol>
</section>
